### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by curtishdev** [Ignaciox/ClearmyInv#1]
Hi, Can you make a plugin, than player leave inventory save, beacouse I have this problem and didn't know how to fix. Pls make good plugin! Bye, have a nice day

**Comment by Veixlix** [comment]
save-playerdata true in pocketmine.yml

**Comment by curtishdev** [comment]
But it's true

**Comment by curtishdev** [comment]
Pls make this plugin ;)

**Comment by Veixlix** [comment]
doesn't work like that. player information shouldn't clear, check for conflicting plugins
